// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsLCUZTs9P_SFn1AKV3CuT4w7SfUKK6xE',
    appId: '1:76266097455:web:682be4b31f1c59b00aefda',
    messagingSenderId: '76266097455',
    projectId: 'loginfirebase-514ee',
    authDomain: 'loginfirebase-514ee.firebaseapp.com',
    storageBucket: 'loginfirebase-514ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcy9PflogKwfSrIPVVgaYBGc33Da2kUKU',
    appId: '1:76266097455:android:042c8d5d385d0d0a0aefda',
    messagingSenderId: '76266097455',
    projectId: 'loginfirebase-514ee',
    storageBucket: 'loginfirebase-514ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUrpa8Wuk0tcVWeMJETZSQE9x2LSQS_VI',
    appId: '1:76266097455:ios:fa1ffdd4a017d4eb0aefda',
    messagingSenderId: '76266097455',
    projectId: 'loginfirebase-514ee',
    storageBucket: 'loginfirebase-514ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUrpa8Wuk0tcVWeMJETZSQE9x2LSQS_VI',
    appId: '1:76266097455:ios:fa1ffdd4a017d4eb0aefda',
    messagingSenderId: '76266097455',
    projectId: 'loginfirebase-514ee',
    storageBucket: 'loginfirebase-514ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsLCUZTs9P_SFn1AKV3CuT4w7SfUKK6xE',
    appId: '1:76266097455:web:1765def7e5d8f87c0aefda',
    messagingSenderId: '76266097455',
    projectId: 'loginfirebase-514ee',
    authDomain: 'loginfirebase-514ee.firebaseapp.com',
    storageBucket: 'loginfirebase-514ee.firebasestorage.app',
  );
}
